"""Generate a self-contained visual report (report.html) from the measured results.

Pure inline SVG — no matplotlib, no CDN, opens offline anywhere. Numbers are the
measured outputs documented in docs/EXPLAINER.md / lessons.md.

  cd demand-forecast && python3 viz.py   # writes report.html
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent


def chart(title, labels, values, fmt="{:.3f}", note="", win=None, suffix=""):
    W, H, pad = 480, 250, 46
    mx = max(values) or 1
    gap = (W - 2 * pad) / len(values)
    bw = gap * 0.62
    bars = []
    for i, (l, v) in enumerate(zip(labels, values)):
        h = (v / mx) * (H - 2 * pad - 18)
        x = pad + i * gap + (gap - bw) / 2
        y = H - pad - h
        color = "#2563eb" if i == win else "#cbd5e1"
        bars.append(f'<rect x="{x:.0f}" y="{y:.0f}" width="{bw:.0f}" height="{h:.0f}" rx="3" fill="{color}"/>')
        bars.append(f'<text x="{x + bw / 2:.0f}" y="{y - 5:.0f}" font-size="11" font-weight="600" '
                    f'text-anchor="middle" fill="#0f172a">{fmt.format(v)}{suffix}</text>')
        for j, part in enumerate(l.split("\n")):
            bars.append(f'<text x="{x + bw / 2:.0f}" y="{H - pad + 14 + j * 11:.0f}" font-size="9.5" '
                        f'text-anchor="middle" fill="#475569">{part}</text>')
    return (f'<div class="card"><h3>{title}</h3>'
            f'<svg viewBox="0 0 {W} {H}" width="100%">'
            f'<line x1="{pad}" y1="{H - pad}" x2="{W - pad}" y2="{H - pad}" stroke="#e2e8f0"/>'
            + "".join(bars) + f'</svg><p class="note">{note}</p></div>')


charts = [
    chart("Exogenous signal = the lever (lift over naive)",
          ["Taxi\n(no signal)", "Olist\n(no signal)", "Rossmann\n(promo)", "M5\n(rel.)", "Bike\n(weather)"],
          [0, 0, 15, 20, 50], fmt="{:.0f}", suffix="%", win=4,
          note="Higher=more lift. Signal wins where it exists; magnitude ÷ baseline strength."),
    chart("recsys @ MovieLens-1M (NDCG@10, higher=better)",
          ["Pop", "ALS", "BPR", "ItemKNN", "Markov", "SASRec"],
          [0.022, 0.034, 0.036, 0.040, 0.082, 0.109], win=5,
          note="Order dominates: both sequence models beat the order-blind MF/KNN."),
    chart("Bike: error falls as signal is added (wMAPE, lower=better)",
          ["Naive", "Seasonal", "GBT\ncalendar", "GBT\n+weather"],
          [0.342, 0.314, 0.218, 0.170], win=3,
          note="Isolation: +calendar −36%, +weather −50% total. The signal is the lever."),
    chart("Accuracy is a DIAL (Olist wMAPE, lower=better)",
          ["state×cat\n×week", "+monthly", "+clusters", "clusters\n+monthly"],
          [0.699, 0.345, 0.339, 0.083], win=3,
          note="8× swing by granularity alone — traded against actionability."),
    chart("Trends: who extrapolates? (Olist 2018, actual=1610)",
          ["Naive\n(lags)", "GBT\n(caps)", "Holt\n(trend)", "Actual"],
          [873, 1219, 1444, 1610], fmt="{:.0f}", win=2,
          note="Trees CAN'T extrapolate (cap ~1219); Holt projects the trend to ~1444."),
    chart("Calibration under drift (coverage, target=0.90)",
          ["Fixed\nconformal", "Adaptive\nconformal", "Target"],
          [0.84, 0.89, 0.90], fmt="{:.2f}", win=1,
          note="Vanilla conformal drifts (0.84); online/adaptive holds target (0.89)."),
]

html = f"""<!doctype html><meta charset=utf-8><title>Demand Forecasting — Explainer</title>
<style>
  body{{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f8fafc;color:#0f172a}}
  header{{background:#0f172a;color:#fff;padding:32px 40px}}
  header h1{{margin:0 0 8px;font-size:24px}} header p{{margin:0;color:#94a3b8;max-width:760px}}
  .syn{{background:#1e293b;color:#e2e8f0;padding:14px 40px;font-size:15px;border-bottom:3px solid #2563eb}}
  .grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(380px,1fr));gap:18px;padding:24px 40px}}
  .card{{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px 18px;box-shadow:0 1px 3px #0001}}
  .card h3{{margin:0 0 6px;font-size:14px;color:#1e293b}}
  .note{{margin:6px 0 0;font-size:12px;color:#64748b}}
  footer{{padding:20px 40px;color:#64748b;font-size:13px}}
</style>
<header><h1>Demand Forecasting — Explainer</h1>
<p>Industry-standard methods × dataset regimes × eval gates. Every number measured on
real data (taxi · Olist · bike · Rossmann · M5), not asserted.</p></header>
<div class=syn><b>Signal is always the lever; the regime decides whether it's enough</b> —
match the method to the regime, and measure everything.</div>
<div class=grid>{''.join(charts)}</div>
<footer>Generated by viz.py · see docs/EXPLAINER.md for the full matrix & run commands.</footer>
"""

(HERE / "report.html").write_text(html)
print(f"wrote {HERE / 'report.html'} ({len(charts)} charts)")
